const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const root=process.env.BLUEFOX_ROOT||path.resolve(__dirname,'..');
const window={BlueFox3D:{},localStorage:{getItem:()=>null,setItem(){},removeItem(){}},addEventListener(){},removeEventListener(){},dispatchEvent(){},setTimeout(){return 0},clearTimeout(){},setInterval(){return 0},clearInterval(){},queueMicrotask(){},performance:{now:()=>0},document:null,CustomEvent:function(t,i){this.type=t;this.detail=i?.detail}};window.window=window;
const BF=window.BlueFox3D;BF.BiblePatterns={SEQUENCE_ACTIONS:{steps:[]},TRAVEL_CYCLE:{steps:[]},NARRATIVE_ONLY:{steps:[],narrativeOnly:true}};BF.maps={rare:{generator:{biomeId:'magnetic',cadence:{rareBiomeForced:true},featuredMicroSceneIds:[]}}};BF.MicroScenes={get(){return null}};
BF.SpecialObjectRuntime={routingNetwork(){return{hub:{mapId:'hub'},destinations:[{mapId:'old-a'},{mapId:'old-b'},{mapId:'new-frontier'}]}}};
const ctx=vm.createContext({window,console,performance:window.performance,CustomEvent:window.CustomEvent,setTimeout:window.setTimeout,clearTimeout:window.clearTimeout,setInterval:window.setInterval,clearInterval:window.clearInterval,Promise});
vm.runInContext(fs.readFileSync(path.join(root,'data/bible-catalog.js'),'utf8'),ctx);let code=fs.readFileSync(path.join(root,'engine/bible-runtime-v0-1-unified.js'),'utf8');code=code.replace(/\n\s*runtime\.start\(\);\n\}\)\(window\);\s*$/,'\n})(window);');vm.runInContext(code,ctx);
const rt=BF.bibleRuntime;assert(rt);const by=new Map(BF.BibleCatalog.map(m=>[m.id,m]));const m1=by.get('EXP-LONG-01'),m2=by.get('EXP-LONG-02'),m3=by.get('EXP-LONG-03'),m5=by.get('EXP-LONG-05');rt.catalog=[m1,m2,m3,m5];rt.byId=new Map(rt.catalog.map(m=>[m.id,m]));
function node(done=false){return{progress:done?1:0,target:1,isComplete:done,increment(n){if(this.isComplete)return false;this.progress=Math.min(this.target,this.progress+n);this.isComplete=this.progress>=this.target;return true}}}
const exp=node(true),remark=node(),study=node(),beacon=node();const tree2={find(id){if(id.endsWith(':explore'))return exp;if(id.endsWith(':remarkable'))return remark;if(id.endsWith(':study'))return study;if(id.endsWith(':deployBeacon'))return beacon;return null},availableLeaves(){if(!remark.isComplete)return[remark];if(!study.isComplete)return[study];if(!beacon.isComplete)return[beacon];return[]},refresh(){}};
const facts={'expLong05:beacon':{mapId:'new-frontier'}};const lifecycle={'EXP-LONG-01':{status:'active'},'EXP-LONG-02':{status:'active'},'EXP-LONG-03':{status:'active'},'EXP-LONG-05':{status:'active'}};const memory={state:{missionLifecycle:lifecycle},getFact(k,d=null){return Object.prototype.hasOwnProperty.call(facts,k)?facts[k]:d},setFact(k,v){facts[k]=v;return true},save(){},saveTree(){}};const manager={memory,trees:new Map([[m2.id,tree2]]),syncLifecycleFromTrees(){},reevaluatePendingActivations(){},catalogController:{schedule(){}},publish(){}};BF.currentEngine={missionManager:manager,currentMapId:'rare'};rt.manager=()=>manager;
assert.equal(rt.reconcileLongExpeditionNavigationTargets(),true);assert.equal(facts['expLong01:hubTarget'].mapId,'hub');assert.equal(facts['expLong05:hubTarget'].mapId,'hub');assert(['old-a','old-b','new-frontier'].includes(facts['expLong03:targetBeacon'].mapId));assert.equal(facts['expLong05:otherBeaconTarget'].mapId,'old-a');
assert.equal(rt.captureLongExpeditionRemarkableMap({isNew:true},{mapId:'rare',biome:'magnetic',featuredMicroSceneIds:[]}),true);assert.equal(facts['expLong02:remarkable'].mapId,'rare');
assert.equal(rt.reconcileLongExpeditionValidations(),true);assert.equal(remark.isComplete,true);
assert.equal(rt.handleLongExpeditionStudyEvent({type:'interaction.analyze',mapId:'rare'}),true);assert.equal(study.isComplete,true);
assert.equal(rt.onSiteEstablished({kind:'deployed_beacon',mapId:'rare',instanceId:'b1'}),true);assert.equal(beacon.isComplete,true);assert.equal(facts['expLong02:beacon'].mapId,'rare');
console.log('PASS EXP-LONG runtime: known TP targets + remarkable/study/beacon validation');
