const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path'); const ROOT=path.join(__dirname,'..');
class CE{constructor(type,init={}){this.type=type;this.detail=init.detail;}}
let NOW=2_000_000; class FakeDate extends Date{static now(){return NOW;}}
const saved={version:1,drones:{harvest_drone:{crafted:true,count:1,active:true}},harvestFleet:[{id:'harvest-1',crafted:true,active:true,inKit:false,deployedMapId:'remote',deployedAnchor:{x:3,y:0,z:4},deployedZoneId:0,deployedZoneLabel:'P1',priority:'collect_all',cargo:{},cargoTotal:0,lastActionAt:1_000_000,workTotal:999,failureCount:0,failure:null,remoteManifest:[{objectId:'COMMON',instanceId:'c1',zoneId:0}]}],resources:{},lastRuntimeAt:1_000_000};
const store=new Map([['bluefox_special_objects_v1',JSON.stringify(saved)]]),listeners=new Map(); const window={console,Date:FakeDate,Math,JSON,Set,Map,WeakMap,Promise,CustomEvent:CE,performance:{now:()=>NOW},localStorage:{getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},addEventListener(t,f){if(!listeners.has(t))listeners.set(t,new Set());listeners.get(t).add(f)},removeEventListener(){},dispatchEvent(e){for(const f of listeners.get(e.type)||[])f(e);return true},document:{querySelector(){return null}},BlueFox3D:{maps:{remote:{id:'remote',zones:['P1']}},ObjectLibrary:{},PersistentMicroScenes:{},Research:{},RuntimeBudget:{shouldUpdate(){return true}}}}; window.window=window; const ctx=vm.createContext(window); const run=f=>vm.runInContext(fs.readFileSync(path.join(ROOT,f),'utf8'),ctx,{filename:f});
run('engine/object-event-registry.js');run('engine/progression-registry.js'); const BF=window.BlueFox3D; const def={id:'COMMON',gameplay:{collectable:true},resource:{family:'ore',inventoryKey:'magnetic_ore'},interaction:{respawnSeconds:30},spawn:{tags:['mineral']}}; BF.ObjectLibrary.getById=id=>id==='COMMON'?def:null;BF.ObjectLibrary.list=()=>[def];BF.PersistentMicroScenes.list=d=>d?.id==='remote'?[{contextRole:'deployed_beacon',persistent:true}]:[];BF.currentEngine={currentMapId:'crystal',currentMap:{group:{children:[],traverse(){}},interactables:[]},character:{root:{position:{x:0,y:0,z:0}}},callbacks:{onStatus(){}}};run('engine/special-object-runtime.js');
const R=BF.SpecialObjectRuntime; R.update({children:[],traverse(){}},0); const d=R.snapshot().harvestFleet[0]; assert.equal(d.workTotal,1000); assert.equal(d.failureCount,1); assert.equal(d.active,false); assert.equal(d.failure.index,1); assert.deepEqual(d.failure.requirements,{accumulator:1}); assert.equal(d.cargoTotal,1,'offline catch-up stops at first threshold');
const collected=BF.getProgressionState().history.filter(e=>e.type==='RESOURCE_COLLECTED').reduce((n,e)=>n+e.quantity,0); assert.equal(collected,1,'no offline work after failure threshold'); assert.equal(BF.getProgressionState().history.filter(e=>e.type==='DRONE_FAILED').length,1);
NOW+=1_000_000; R.update({children:[],traverse(){}},0); assert.equal(BF.getProgressionState().history.filter(e=>e.type==='RESOURCE_COLLECTED').reduce((n,e)=>n+e.quantity,0),1,'failed drone remains stopped');
console.log('PASS R4-B offline work stops exactly at deterministic failure threshold');
