const assert=require('node:assert/strict');
const fs=require('node:fs');
const planner=fs.readFileSync('engine/mission-planner.js','utf8');
const manager=fs.readFileSync('engine/mission-manager.js','utf8');
const bible=fs.readFileSync('engine/bible-runtime-v0-1-unified.js','utf8');
assert.match(planner,/requiredMapState\(node, context = \{\}\)/);
assert.match(planner,/if \(mapState\.constrained && !mapState\.runnable\) return -100/);
assert.match(manager,/primaryEventDrivenTravel\(\)/,'existing explicit TRAVEL owner must remain');
assert.match(manager,/primaryMissionTransition\(context = this\.bridge\.context\(\)\)/);
assert.match(manager,/transition && this\.missionTransitionExecutable\(transition\)/);
assert.match(manager,/this\.delegatedRuntimeAction\(this\.primaryMissionId\)/);
assert.match(manager,/return this\.hasRunnablePrimaryMission\(\)/);
assert.match(manager,/wakeIdleRetry\(/);
assert.match(manager,/this\.idleRetryUntil = this\.retryAfter/,'only no-action backoff is tagged wakeable');
assert.match(bible,/bibleDeferredTrigger:/,'deferred trigger causal evidence must live in MissionMemory facts');
assert.match(bible,/this\.manager\(\)\?\.startMission\?\./,'deferred trigger must use canonical MissionManager lifecycle');
assert.match(bible,/targetMapId: targetMapId \|\| null/,'remote completion gate must expose its map to MissionManager');
assert.equal((planner.match(/setInterval\s*\(/g)||[]).length,0);
assert.equal((manager.match(/setInterval\s*\(/g)||[]).length,0);
assert.equal((bible.match(/setInterval\s*\(/g)||[]).length,0,'BibleRuntime remains event-driven: no polling loop');
assert.doesNotMatch(manager,/ObjectEvents\.subscribe|addEventListener\([^\n]*Object/,'MissionManager must not add a parallel ObjectEvents listener');
console.log('PASS R-STAB static owners / no new polling / preserved travel contract');
