const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const vm=require('node:vm'); const path=require('node:path');
const root=path.resolve(__dirname,'..'); const context={console:{info(){},warn(){},error(){}}}; context.window=context; vm.createContext(context); vm.runInContext(fs.readFileSync(path.join(root,'data','bible-catalog.js'),'utf8'),context); const byId=id=>context.BlueFox3D.BibleCatalog.find(m=>m.id===id);

test('ARCH-R4: 11 missions présentes et chaîne 19→29',()=>{const ids=Array.from({length:11},(_,i)=>`ARCH-${19+i}`); ids.forEach(id=>assert.ok(byId(id),id)); for(let i=20;i<=29;i++) assert.deepEqual(Array.from(byId(`ARCH-${i}`).prerequisites),[`ARCH-${i-1}`]);});
test('ARCH-19: machine abandonnée = arme narrative, simple observation',()=>{const m=byId('ARCH-19'); assert.equal(m.mapGeneration.requiredMicroScenes[0].id,'MSC-CUSTOM-MACHINE-ABANDONNEE'); const w=m.sequence.find(x=>x.slot==='weapon'); assert.equal(w.action,'observe'); assert.equal(w.params.cuoType,'ancient_machine_wreck');});
test('ARCH-24: 15 collectes composants/core via types collectables',()=>{const m=byId('ARCH-24'),[a,b]=m.sequence; assert.equal(a.action,'collect'); assert.equal(b.action,'collect'); assert.equal(a.target+b.target,15); for(const s of [a,b]) assert.deepEqual(Array.from(s.params.cuoTypes),['relay_block','pulse_core','memory_capsule','logic_prism']);});
test('ARCH-25: 2 nouvelles maps puis 50% de la seconde map bindée',()=>{const m=byId('ARCH-25'),s=m.sequence.find(x=>x.slot==='coverage'); assert.equal(m.trigger.type,'exploration.map_discovered'); assert.equal(m.trigger.count,2); assert.equal(m.trigger.uniqueOnly,true); assert.equal(m.bindActivationMap,true); assert.equal(s.params.threshold,50); assert.equal(s.params.requiredMapFact,'bibleActivation:ARCH-25');});
test('ARCH-27: deux objets distincts sur la même MSC que ARCH-26',()=>{const a=byId('ARCH-26'),b=byId('ARCH-27'); assert.equal(a.mapGeneration.requiredMicroScenes[0].id,'MSC-CUSTOM-FOYER-ANCIEN'); const [first,second]=b.sequence; assert.equal(first.params.microSceneId,'MSC-CUSTOM-FOYER-ANCIEN'); assert.equal(second.params.microSceneId,'MSC-CUSTOM-FOYER-ANCIEN'); assert.equal(first.target+second.target,2); assert.deepEqual(Array.from(second.params.relation.differentBy),['instanceId']);});
test('ARCH-22/23 respectent les déclencheurs deux maps et les MSC prévues',()=>{const a=byId('ARCH-22'),b=byId('ARCH-23'); assert.equal(a.trigger.count,2); assert.equal(a.mapGeneration.requiredMicroScenes[0].id,'MSC-CUSTOM-ASTROLOGY'); assert.equal(b.trigger.count,2); assert.equal(b.trigger.direction,'south'); assert.equal(b.mapGeneration.requiredMicroScenes[0].id,'MSC-TECH-RELAY-001');});
test('ARCH-20: voyage autonome garanti avant la relique scientifique',()=>{const m=byId('ARCH-20'); assert.equal(m.navigation.autonomousUnknownTravel,true); assert.equal(m.navigation.singleUnknownTransition,true); const [travel,relic]=m.sequence; assert.equal(travel.slot,'travel'); assert.equal(travel.action,'travel'); assert.equal(travel.params.eventDriven,true); assert.equal(travel.params.newOnly,true); assert.deepEqual(Array.from(relic.requires),['travel']); assert.equal(m.mapGeneration.requiredMicroScenes[0].id,'MSC-CUSTOM-HAUTEL-STELL-RELIC-COMP');});
test('ARCH-29: 4 habitats composites puis HABITAT-RUINE en 5e unité sur 3 nouvelles maps',()=>{const m=byId('ARCH-29'); assert.equal(m.pattern,'SEQUENCE_ACTIONS'); assert.equal(m.trigger.type,'progression.mission_completed'); assert.equal(m.trigger.missionId,'ARCH-28'); assert.equal(m.navigation.autonomousUnknownTravel,true); const travels=m.sequence.filter(x=>x.action==='travel'); const habitats=m.sequence.filter(x=>x.slot.startsWith('habitat')); assert.equal(travels.length,3); assert.equal(habitats.length,5); const perTravel=travels.map(t=>Array.from(t.params.mapGenerationOnCount[1].requiredMicroScenes,x=>x.id)); assert.deepEqual(JSON.parse(JSON.stringify(perTravel)),[['MSC-CUSTOM-HABITAT-VESTIGE-01','MSC-CUSTOM-HABITAT-VESTIGE-02'],['MSC-CUSTOM-HABITAT-VESTIGE-03','MSC-CUSTOM-HABITAT-VESTIGE-04'],['MSC-CUSTOM-HABITAT-RUINE']]); const staged=perTravel.flat(); assert.ok(travels.flatMap(t=>Array.from(t.params.mapGenerationOnCount[1].requiredMicroScenes)).every(x=>x.spawnOnce===true)); assert.deepEqual(Array.from(habitats,x=>x.params.microSceneId),JSON.parse(JSON.stringify(staged))); assert.equal(habitats.at(-1).params.microSceneId,'MSC-CUSTOM-HABITAT-RUINE');});
