const fs=require('fs');
const vm=require('vm');
const path=require('path');
const assert=require('assert');
const ROOT=path.join(__dirname,'..');
const basePath=process.argv[2]?path.resolve(process.argv[2]):path.resolve('/mnt/data/cart_base/data/bible-catalog.js');
const candPath=process.argv[3]?path.resolve(process.argv[3]):path.join(ROOT,'data/bible-catalog.js');
function load(p){const window={BlueFox3D:{}};window.window=window;vm.runInNewContext(fs.readFileSync(p,'utf8'),window,{filename:p});return window.BlueFox3D.BibleCatalog;}
const base=load(basePath), cand=load(candPath);
assert.equal(base.length,287,'HEAD ff7a1687 attendu à 287 missions');
assert.ok(cand.length>=290,'CART exige au moins les 290 missions acquises après son lot');
const baseIds=Array.from(base,m=>m.id), candIds=Array.from(cand,m=>m.id);
const stripped=candIds.filter(id=>!['CART-02','CART-01','CART-03'].includes(id));
const preserved=stripped.filter(id=>baseIds.includes(id));
assert.deepStrictEqual(preserved,baseIds,'les 287 missions du HEAD CART de référence doivent être strictement préservées dans le même ordre');
const byId=new Map(cand.map(m=>[m.id,m]));
for(const id of ['CART-02','CART-01','CART-03']) assert(byId.has(id),`${id} absente`);
const c2=byId.get('CART-02'), c1=byId.get('CART-01'), c3=byId.get('CART-03');
assert.deepStrictEqual(Array.from(c2.prerequisites),['PHEN-01']);
assert.equal(c2.trigger.missionId,'PHEN-01');
assert.equal(c2.mapGeneration.biome,'swamp');
assert.equal(c2.mapGeneration.requiredObjects[0].type,'fog_bank');
assert.equal(c2.mapGeneration.requiredObjects[0].count,2);
const c2By=Object.fromEntries(c2.sequence.map(s=>[s.slot,s]));
assert.deepStrictEqual(Array.from(c2.sequence.map(s=>s.slot)),['reach','bluefoxFog','scoutConfirm','explore','distribution']);
assert.equal(c2By.bluefoxFog.params.actor,'bluefox');
assert.equal(c2By.scoutConfirm.params.actor,'scout');
assert.equal(c2By.scoutConfirm.params.remote,false);
assert.deepStrictEqual(Array.from(c2By.scoutConfirm.params.relation.sameBy),['instanceId']);
assert.equal(c2By.distribution.params.distinctBy,'instanceId');
assert.equal(c2By.distribution.target,2);
assert(!JSON.stringify(c2).includes('weather_sensor'));
assert(!JSON.stringify(c2).includes('weather_phenomenon_support'));
assert.deepStrictEqual(Array.from(c1.prerequisites),['CART-02']);
assert.equal(c1.trigger.missionId,'CART-02');
assert.equal(c1.mapGeneration.biome,'crystalline');
assert.deepStrictEqual(Array.from(c1.mapGeneration.requiredObjects.map(o=>o.type)),['crystal','resonant_basalt','needle']);
const c1By=Object.fromEntries(c1.sequence.map(s=>[s.slot,s]));
assert.deepStrictEqual(Array.from(c1.sequence.map(s=>s.slot)),['reach','explore','analyzeCrystal','analyzeBasalt','analyzeNeedle','scoutCrystal','scoutBasalt','scoutNeedle']);
assert.equal(c1By.analyzeCrystal.params.cuoType,'crystal');
assert.equal(c1By.analyzeBasalt.params.cuoType,'resonant_basalt');
assert.equal(c1By.analyzeNeedle.params.cuoType,'needle');
assert.equal(c1By.scoutCrystal.params.actor,'scout');
assert.equal(c1By.scoutBasalt.params.actor,'scout');
assert.equal(c1By.scoutNeedle.params.actor,'scout');
assert.equal(c1By.scoutCrystal.params.cuoType,'crystal');
assert.equal(c1By.scoutBasalt.params.cuoType,'resonant_basalt');
assert.equal(c1By.scoutNeedle.params.cuoType,'needle');
assert(!JSON.stringify(c1).includes('distinctBy\\\":\\\"cuoType'),'CART-01 ne doit pas utiliser un mode distinctBy non supporté par ObjectM0');
const c1Json=JSON.stringify(c1);
for(const forbidden of ['sound_crystal','acoustic_event','sound_measurement','geology_expertise','geological_resource_support']) assert(!c1Json.includes(forbidden),`pseudo-capacité interdite: ${forbidden}`);
assert.deepStrictEqual(Array.from(c3.prerequisites),['CART-01']);
assert.equal(c3.trigger.missionId,'CART-01');
assert.equal(c3.mapGeneration.requiredObjects[0].type,'fog_bank');
const c3By=Object.fromEntries(c3.sequence.map(s=>[s.slot,s]));
assert.deepStrictEqual(Array.from(c3.sequence.map(s=>s.slot)),['reachReference','reference','regionalSurvey','synthesis']);
assert.equal(c3By.reference.params.actor,'bluefox');
assert.equal(c3By.regionalSurvey.params.actor,'scout');
assert.equal(c3By.regionalSurvey.params.distinctBy,'mapId');
assert.equal(c3By.regionalSurvey.target,3);
assert.deepStrictEqual(Array.from(c3By.regionalSurvey.params.cuoTypes),['fog_bank','electrostatic_storm']);
assert.equal(c3By.regionalSurvey.params.remote,undefined,'local + distant doivent rester acceptés pour rendre trois maps atteignables');
for(const id of ['PHEN-01','PHEN-02','PHEN-03','PHEN-04','PHEN-05','PHEN-06','PHEN-07','PHEN-08','PHEN-09','PHEN-10','PHEN-11','PROS-01','PROS-03','PROS-02']) assert(byId.has(id),`${id} doit être préservée`);
console.log('CART IMI contract: PASS');
