const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
class V3{constructor(x=0,y=0,z=0){this.x=x;this.y=y;this.z=z;}clone(){return new V3(this.x,this.y,this.z)}copy(v){this.x=v.x;this.y=v.y;this.z=v.z;return this}set(x,y,z){this.x=x;this.y=y;this.z=z;return this}setY(y){this.y=y;return this}sub(v){this.x-=v.x;this.y-=v.y;this.z-=v.z;return this}addScaledVector(v,s){this.x+=v.x*s;this.y+=v.y*s;this.z+=v.z*s;return this}distanceTo(v){return Math.hypot(this.x-v.x,this.y-v.y,this.z-v.z)}lengthSq(){return this.x*this.x+this.y*this.y+this.z*this.z}normalize(){const l=Math.hypot(this.x,this.y,this.z)||1;this.x/=l;this.y/=l;this.z/=l;return this}lerpVectors(a,b,t){this.x=a.x+(b.x-a.x)*t;this.y=a.y+(b.y-a.y)*t;this.z=a.z+(b.z-a.z)*t;return this}applyAxisAngle(){return this}cross(){return this}}

test('BAC prudent + FaunaRuntime: l autonomie atteint l interaction sans fuite',()=>{
 let pnow=1000,raf=null,interactions=0;const hooks=[];const animal={position:new V3(0,0,0),rotation:new V3(),scale:new V3(1,1,1),children:[],parent:{},visible:true,userData:{active:true,libraryType:'brouteur',functional:{type:'brouteur',category:'fauna',spawn:{tags:['fauna']},interaction:{actions:['observe']}}},traverse(fn){fn(this)}};animal.userData.worldAnchor=animal;
 const character={root:{position:new V3(8,0,0)},target:new V3(8,0,0),speed:0,fatigueSpeedMultiplier:1,setTarget(p,m){this.target=p.clone();this.mode=m;return true},stop(){this.speed=0}};character.setTarget=character.setTarget.bind(character);character.stop=character.stop.bind(character);
 const engine={character,THREE:{Vector3:V3},currentMapId:'m',currentMap:{interactables:[animal],gates:[]},discoveredMaps:new Set(),transitioning:false,pendingInteraction:null,pendingGate:null,pendingZoneExploration:null,currentRoutine:null,postActionRecoveryUntil:0,lastAutonomyAt:0,lastActivityAt:0,autonomyActionStreak:0,autonomyBreakTarget:3,missionManager:{currentAction:null,memory:{state:{missionLifecycle:{}}},hasPrimaryMissionAuthority(){return false}},canInteractWith(){return true},interactionProfile(){return {action:'observe'}},interactionApproachPoint(){return {point:new V3(1.5,0,0),pathLength:6}},targetInteraction(){interactions++;return true},updateAutonomy(){},ensureActivity(){},noteLocalAutonomousDecision(){},showWorldMarker(){},callbacks:{onStatus(){}},canStartAutonomousGate(){return false}};
 const BF={currentEngine:engine,Missions:{},ObjectLibrary:{create(){},exists(){return false},get(){return null},registerCreateHook(fn){hooks.push(fn)}},PassiveObjectRuntime:{setEnabled(){}},ObjectEvents:{types:{},history(){return[]}},BAC:{evaluateSurvivalDecision(){return null},weightedPick(opts){return opts.find(o=>o.id==='relations-object')}},getSurvivalState(){return {fatigue:{movement:1},needs:{}}},getMapExplorationState(){return {surfacePercent:20}},getNextUnexploredMapTarget(){return null}};
 const ctx={window:null,BlueFox3D:BF,performance:{now:()=>pnow},Date,Math,Set,Map,WeakMap,Object,console:{info(){},error(){},warn(){}},requestAnimationFrame(fn){raf=fn;return 1},document:{querySelector(){return {classList:{contains(){return false}}}}},addEventListener(){},setTimeout(fn){fn()},setInterval(){return 1},clearInterval(){}};ctx.window=ctx;vm.createContext(ctx);
 vm.runInContext(fs.readFileSync(path.join(__dirname,'..','engine','fauna-runtime.js'),'utf8'),ctx);BF.FaunaRuntime.register(animal,'brouteur');
 vm.runInContext(fs.readFileSync(path.join(__dirname,'..','engine','behavior-arbitration-integration.js'),'utf8'),ctx);
 const fauna=(ms,pos,speed)=>{pnow=1000+ms;if(typeof pos==='number')character.root.position.x=pos;else character.root.position.copy(pos);character.speed=speed;raf();};
 engine.updateAutonomy(6000);assert.equal(character.mode,'walk');
 fauna(6200,6.5,2);fauna(6800,5.4,1.8);fauna(7200,4.8,0);engine.updateAutonomy(7200);for(let ms=7400;ms<=8400;ms+=200)fauna(ms,4.8,0);engine.updateAutonomy(8500);assert.ok(Math.abs(character.target.distanceTo(animal.position)-3)<.03);const inner=character.target.clone();const halfway=character.root.position.clone().addScaledVector(inner.clone().sub(character.root.position),.5);
 fauna(8700,halfway,1.8);fauna(9100,inner,0);engine.updateAutonomy(9100);fauna(9300,inner,0);assert.equal(BF.FaunaRuntime.getState(animal).acceptedProximity,true);engine.updateAutonomy(10000);assert.equal(interactions,1);
 fauna(10200,2.4,2.5);fauna(10600,1.5,2.5);assert.notEqual(BF.FaunaRuntime.getState(animal).state,'flee');
});
