const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..'); const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
class CE{constructor(type,o={}){this.type=type;this.detail=o.detail}}
function boot(){
 const listeners=new Map(),store=new Map();
 const window={BlueFox3D:{},CustomEvent:CE,console,performance,Date,Math,JSON,Set,Map,WeakMap,Promise,queueMicrotask,
 localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},
 addEventListener(t,f){if(!listeners.has(t))listeners.set(t,new Set());listeners.get(t).add(f)},removeEventListener(t,f){listeners.get(t)?.delete(f)},dispatchEvent(e){for(const f of [...(listeners.get(e.type)||[])])f(e);return true},setTimeout(){return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){}};window.window=window;
 const ctx=vm.createContext({window,CustomEvent:CE,console,performance,Date,Math,JSON,Set,Map,WeakMap,Promise,queueMicrotask,setTimeout:window.setTimeout,clearTimeout:window.clearTimeout,setInterval:window.setInterval,clearInterval:window.clearInterval});
 const load=(p,strip=false)=>{let s=read(p); if(strip)s=s.replace(/\n\s*const runtime = new BibleRuntimeV01\(\);[\s\S]*?runtime\.start\(\);\s*\n\}\)\(window\);\s*$/,'\n  BF.BibleRuntimeV01 = BibleRuntimeV01;\n})(window);'); vm.runInContext(s,ctx,{filename:p});};
 ['engine/mission-types.js','engine/mission-tree.js','engine/mission-memory.js','engine/mission-planner.js','engine/action-bridge.js'].forEach(p=>load(p));
 load('data/bible-catalog.js');
 const BF=window.BlueFox3D, M=BF.Missions;
 const ids=['KEEP','T08','T13','FLO-02','ENV-RELIC-20','ENV-ROCK-20','ENV-PLANT-20','ENV-WORLD-10','BAL-03','ENE-13','DRN-01','POSTDIP-01','ENE-15-C','TP-01'];
 const defs={};
 for(const id of ids){const cat=BF.BibleCatalog.find(m=>m.id===id);defs[id]={id,title:cat?.title||id,priority:Number(cat?.priority)||1,experimentalPrerequisites:cat?.experimentalPrerequisites?[...cat.experimentalPrerequisites]:undefined,root:{id:id+':root',title:id,type:'group',target:1,children:[{id:id+':step',title:'step',type:'observe',target:1,params:{},requires:[]}]}}}
 BF.registerMissionDefinitions(Object.values(defs));
 load('engine/mission-manager.js');
 const pos={x:0,y:0,z:0,distanceTo(){return 0}}; const engine={currentMapId:'crystal',currentMap:{interactables:[],zoneRegions:[]},discoveredZones:new Set(),character:{root:{position:pos},target:pos},callbacks:{onAction(){},onStatus(){}},pendingInteraction:null,currentRoutine:null,pendingGate:null,pendingZoneExploration:null,transitioning:false};
 const manager=M.MissionManager.create({engine}); engine.missionManager=manager; BF.currentEngine=engine; BF.getMissionState=()=>manager.getState(); BF.getExplorationSummary=()=>({maps:{}}); BF.getMapExplorationState=()=>({surfacePercent:0}); BF.getSurvivalState=()=>({energy:100,needs:{}});
 load('engine/bible-runtime-v0-1-unified.js',true); const runtime=Object.create(BF.BibleRuntimeV01.prototype); runtime.catalog=BF.BibleCatalog;runtime.byId=new Map(runtime.catalog.map(m=>[m.id,m]));runtime.dynamicMissions=new Map();runtime.state={triggerCounts:{},uniqueTriggerValues:{},progressNarrative:{},effectsApplied:{},gatesSatisfied:{},activationInventoryCredits:{},constructionInstances:{},localMissionInstances:{},faunaMissionInstances:{}}; runtime.saveState=()=>true;runtime.missionLifecycleStatuses=new Map(); runtime.refreshProximityContextMonitor=()=>false; runtime.emitRevealedOnce=()=>true; runtime.initializeRuntimeCounters=()=>false; runtime.reconcileRuntimeCounters=()=>0; runtime.reconcileHistoricalCollections=()=>false; BF.bibleRuntime=runtime;
 manager.ensureLifecycle('T08').status='completed';
 return {BF,manager,runtime};
}

test('T13 real MissionManager fanout: FLO primary allowed, ENV followers active secondary',()=>{const h=boot(); const {manager,runtime}=h; manager.ensureLifecycle('T13').status='completed'; const r=runtime.consumeTriggerEvent({type:'progression.mission_completed',missionId:'T13',mapId:'crystal'}); const due=['FLO-02','ENV-RELIC-20','ENV-ROCK-20','ENV-PLANT-20','ENV-WORLD-10']; for(const id of due) assert.equal(manager.ensureLifecycle(id).status,'active',id); assert.equal(manager.primaryMissionId,'FLO-02'); assert.deepEqual([...r.activatedMissionIds].sort(),[...due].sort()); for(const id of due.slice(1)) assert.notEqual(manager.primaryMissionId,id);});

test('historical deferred pending must remain owned by MissionManager until canonical reevaluation',()=>{const h=boot();const {BF,manager,runtime}=h; manager.startMission('KEEP',{primary:true}); manager.ensureLifecycle('BAL-03').status='completed';manager.ensureLifecycle('ENE-13').status='completed';let unlocked=false;runtime.isResearchRewardUnlocked=id=>id==='reverse_engineering'?unlocked:false; runtime.catalog=[runtime.byId.get('DRN-01')]; const r=runtime.consumeTriggerEvent({type:'progression.mission_completed',missionId:'BAL-03',mapId:'crystal'}); assert.ok(manager.memory.state.pendingActivations['DRN-01'],'DRN pending must exist'); assert.equal(manager.ensureLifecycle('DRN-01').status,'hidden'); unlocked=true; const before=manager.memory.state.pendingActivations['DRN-01']; assert.ok(before); const changed=runtime.reconcileDeferredCompletionTriggers(); assert.equal(changed,false,'BibleRuntime must not consume historical MissionManager pending receipt'); assert.ok(manager.memory.state.pendingActivations['DRN-01'],'pending must remain until manager reevaluation'); assert.equal(manager.ensureLifecycle('DRN-01').status,'hidden'); assert.equal(manager.reevaluatePendingActivations(),true); assert.equal(manager.ensureLifecycle('DRN-01').status,'active'); assert.equal(manager.primaryMissionId,'KEEP','secondary pending must not steal Top1');});

test('TP-01 fact-only deferred receipt activates after fact while preserving existing primary',()=>{const h=boot();const {manager,runtime}=h;manager.startMission('KEEP',{primary:true});manager.ensureLifecycle('POSTDIP-01').status='completed';manager.ensureLifecycle('ENE-15-C').status='completed';const key='civilization:research:teleport-hypothesis-v1';assert.equal(manager.memory.getFact(key,false),false);runtime.catalog=[runtime.byId.get('TP-01')]; runtime.consumeTriggerEvent({type:'progression.mission_completed',missionId:'POSTDIP-01',mapId:'crystal'});assert.equal(manager.ensureLifecycle('TP-01').status,'available');assert.ok(manager.memory.getFact('bibleDeferredTrigger:TP-01',null));manager.memory.setFact(key,{at:1});assert.equal(runtime.reconcileDeferredCompletionTriggers(),true);assert.equal(manager.ensureLifecycle('TP-01').status,'active');assert.equal(manager.primaryMissionId,'KEEP');});
