const fs=require('fs'),assert=require('assert'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const catalog=fs.readFileSync(path.join(ROOT,'engine/mission-catalog.js'),'utf8');
const npc=fs.readFileSync(path.join(ROOT,'engine/npc-runtime.js'),'utf8');
const cityData=fs.readFileSync(path.join(ROOT,'data/civilization-cities.js'),'utf8');
assert(catalog.includes('custom-map-31-tinycity'),'TinyCity is the translucent capital');
assert(catalog.includes('custom-map-32-rock-village'),'Rock village map is integrated');
assert(cityData.includes('civilizationRole = "city"'),'city role is explicit in city data owner');
assert(catalog.includes('npcRole: "merchant"'),'merchant is an instance role');
assert(cityData.includes('custom-map-30-village')===false,'ARCH village is not redefined by civilization city data');
assert(catalog.includes('quantum-geographic-marker-blueprint-v1'),'Rocky blueprint exists');
assert(catalog.includes('fragmenter-assembler-blueprint-v1'),'Translucent blueprint exists');
assert(/inventoryKey: "energy_crystal", quantity: 25/.test(catalog),'Rocky blueprint costs 25 blue energy crystals');
assert(/provenance: "prismatic_orchid", quantity: 25/.test(catalog),'Translucent blueprint requires 25 prism orchid units');
assert(catalog.includes('requiresFurtherExperimentation: true'),'teleportation remains an experimentation hypothesis');
assert(catalog.includes('unlocksTeleporter: false'),'R3 explicitly does not unlock a teleporter');
assert(catalog.includes('text/bluefox-trade-key'),'trade UI uses drag/drop payloads');
assert(catalog.includes('Confirmer l’échange'),'trade UI keeps explicit confirmation');
assert(catalog.includes('Réservé au rang HONORÉ'),'blueprint stays visible but disabled before max reputation');
assert(!/teleport\s*\(/.test(catalog),'R3 contains no teleport implementation');
assert(npc.includes('npcRole:'),'NPC_CONTACTED propagates the instance role');
console.log('PASS npc-r3-contract');
