const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
class V{constructor(x=0,y=0,z=0){this.x=x;this.y=y;this.z=z}clone(){return new V(this.x,this.y,this.z)}}
class Group{constructor(){this.userData={};this.children=[];this.position={set(){}};this.rotation={set(){}}}add(x){this.children.push(x)}}
const spawned=[];let microSceneCalls=0;
class Spawner{constructor(o){this.o=o}spawn(type,opts){const root={userData:{},position:new V(opts.position.x,opts.position.y,opts.position.z),updateWorldMatrix(){},localToWorld(v){return new V(v.x+this.position.x,v.y+this.position.y,v.z+this.position.z)}};const hitbox={userData:{}};const record={type,root,instance:{hitbox,colliders:[{offset:new V(),radius:.5}]}};spawned.push({type,opts,record});return record}spawnMicroScene(){microSceneCalls+=1;return[]}}
const built={group:new Group(),interactables:[],colliders:[]};
const window={console,Math,BlueFoxCustomMaps:[{id:'custom-map-31-tinycity',name:'TinyCity',plateauCount:1,palette:{},customMicroScenes:[]}],BlueFox3D:{maps:{},ObjectSpawner:Spawner,buildMap(){return {group:new Group(),interactables:[],colliders:[]}}}};window.window=window;
const ctx=vm.createContext(window);vm.runInContext(fs.readFileSync(path.join(ROOT,'data/civilization-cities.js'),'utf8'),ctx);vm.runInContext(fs.readFileSync(path.join(ROOT,'engine/custom-map-registry.js'),'utf8'),ctx);
const BF=window.BlueFox3D;const rock=BF.maps['custom-map-32-rock-village'];assert(rock);const rockBuilt=BF.buildMap({Group},rock,null,null);const merchantSpawn=spawned.find(x=>x.type==='npc_rocky');assert(merchantSpawn,'rock city builds a fixed Rocky merchant');assert.equal(merchantSpawn.opts.position.x,10.5);assert.equal(merchantSpawn.opts.position.z,3.3);assert.equal(merchantSpawn.record.root.userData.npcRole,'merchant');assert.equal(merchantSpawn.record.root.userData.civilizationId,'rocky');assert.equal(rockBuilt.interactables.length,1);assert.equal(rockBuilt.colliders.length,1);assert.equal(microSceneCalls,rock.customMicroScenes.length,'existing customMicroScenes pipeline is preserved');
spawned.length=0;const tiny=BF.maps['custom-map-31-tinycity'];const tinyBuilt=BF.buildMap({Group},tiny,null,null);const translucent=spawned.find(x=>x.type==='npc_translucent');assert(translucent,'TinyCity builds a fixed Translucent merchant');assert.equal(translucent.record.root.userData.npcRole,'merchant');assert.equal(translucent.record.root.userData.civilizationId,'translucent');assert.equal(tinyBuilt.interactables.length,1);
console.log('PASS npc-r3-merchant-spawn');
