const fs=require('fs'); const assert=require('assert'); const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const obj=fs.readFileSync(path.join(ROOT,'engine/object-library-p2-1.js'),'utf8');
const rt=fs.readFileSync(path.join(ROOT,'engine/npc-runtime.js'),'utf8');
const map=fs.readFileSync(path.join(ROOT,'map-test/index.html'),'utf8');
const city=fs.readFileSync(path.join(ROOT,'data/civilization-cities.js'),'utf8');
const cuo=fs.readFileSync(path.join(ROOT,'cuo-lab/index.html'),'utf8');
for(const joint of ['TranslucentElbow','TranslucentKnee','RockyElbow','RockyKnee']) assert(obj.includes(joint),`joint missing ${joint}`);
assert(obj.includes('groundNpcVisual(THREE, root, 0.35)'),'translucent model scale 0.35');
assert(obj.includes('groundNpcVisual(THREE, root, 0.47)'),'rocky model scale 0.47');
assert(obj.includes('new THREE.Box3().setFromObject(root)'),'grounding computed from visible model bounds before hitbox');
assert(!rt.includes('applyVisualCalibration'),'NpcRuntime no longer owns visual transform calibration');
assert(rt.includes('Math.atan2(-dz, dx)'),'motion/player facing uses +X model front axis');
assert(rt.includes('syncKinematics(state)'),'kinematic joint synchronization active');
assert(rt.includes('dialogueEnvelope'),'dialogue gesture envelope active');
assert(rt.includes('FORWARD_FOREARM_ANGLE = Math.PI / 2'),'dialogue bends forearm forward to approximately 90 degrees');
assert(rt.includes('yawAmplitude = vigilant ? 0.34'),'vigilance head motion visibly amplified');
assert(obj.includes('handAnchor.add(hand)') && obj.includes('handAnchor.add(digit)'),'translucent hand and fingers share a moving hand anchor');
assert(obj.includes('plate.userData.jointRole = "elbow"'),'Rocky elbow decoration identified on both side-generated arms');
assert(rt.includes('syncRockyElbowDecor(state)'),'Rocky elbow decorations follow both elbow joints');
assert((city.match(/position: Object\.freeze\(\[-36, 0, -20\]\)/g)||[]).length===2,'TinyCity merchant uses visually validated plateau position');
assert(rt.includes('state.lookBlend += (strength - state.lookBlend) * 0.18'),'player tracking response amplified');
for(const action of ['rest','calm','vigilance','dialogue','track','flee','return']) assert(map.includes(`data-npc-test="${action}"`),`MAP_Test control missing ${action}`);
assert(map.includes('Joueur test en orbite'),'MAP_Test tracking demo present');
assert(cuo.includes('../engine/object-library-p2-1.js?v=npc-r45-relational-visibility') && cuo.includes('../engine/npc-runtime.js?v=npc-r45-relational-visibility'),'CUO Lab must load current NPC visual/runtime assets');
assert(rt.includes('npcMissionContactMode'),'ARCH-R5 contact mode producer preserved');
assert(rt.includes('emitNpcReaction'),'ARCH-R5 NPC reaction producer preserved');
assert(rt.includes('reactToApproach(root, options = {})'),'ARCH-R5 approach reaction API preserved');
console.log('PASS npc-r4-animation-contract');
