const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=path.resolve(__dirname,'..');
const rt=fs.readFileSync(path.join(ROOT,'engine/npc-runtime.js'),'utf8');
const events=fs.readFileSync(path.join(ROOT,'engine/object-event-registry.js'),'utf8');
const catalog=fs.readFileSync(path.join(ROOT,'engine/mission-catalog.js'),'utf8');
assert(events.includes('NPC_CONTACTED: "NPC_CONTACTED"'),'canonical NPC_CONTACTED event missing');
assert(events.includes('NPC_DIALOGUE: "NPC_DIALOGUE"'),'canonical NPC_DIALOGUE event missing');
assert(rt.includes('CIVILIZATION_BY_TYPE'),'explicit civilization mapping missing');
assert(rt.includes('BF.ObjectEvents?.types?.NPC_CONTACTED'),'real NPC contact not emitted by NpcRuntime');
assert(rt.includes('NpcSpeechBubble'),'world-space NPC speech bubble missing');
assert(rt.includes('relationRank'),'NpcRuntime does not consume relation rank');
assert(catalog.includes('MissionCatalogController'),'existing catalog owner not generalized');
assert(catalog.includes('civilization:relation:'),'persistent relation fact key missing');
assert(catalog.includes('honoredAcceptedThreshold'),'HONORED threshold must be configurable/exposed');
assert(catalog.includes('passivePriorityAxis: "civilization"'),'Civilisation BAC axis missing');
assert(catalog.includes('BF.grantInventory?.'),'physical mission reward must use canonical inventory grant');
assert(catalog.includes('rearmRepeatableMission'),'service missions must reuse repeatable lifecycle');
for (const bad of ['ContactRuntime','CivilizationMissionManager','PathPlanner']) assert(!catalog.includes(bad),`parallel owner leaked: ${bad}`);
console.log('PASS npc-r2-contract');
