const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const ROOT=path.join(__dirname,'..');
const objectFile=path.join(ROOT,'engine/object-m0-bridge.js');
const listeners=new Map(); const events=[];
class CE{constructor(type,o={}){this.type=type;this.detail=o.detail;}}
class Memory{constructor(){this.state={missionLifecycle:{},missions:{},activeMissionIds:[],primaryMissionId:'',activeMissionId:'',pendingActivations:{},researchUnlocks:{},siteProgression:{}};this.facts={};this.processed=new Set();}save(){} saveTree(t){this.state.missions[t.id]=t.toJSON();} remember(){} getFact(k,d=null){return this.facts[k]??d} setFact(k,v){this.facts[k]=v} recordEffectReceipt(){} hasProcessedObjectEvent(id){return this.processed.has(id)} markProcessedObjectEvent(id){this.processed.add(id)} }
class Node{constructor(raw){this.id=raw.id;this.type=raw.type;this.target=raw.target||1;this.progress=0;this.params=raw.params||{};this.requires=raw.requires||[];this.status='available';this.children=[];this.completedAt=0;this.historyValues=[];this.distinctValues=[];}get isComplete(){return this.progress>=this.target} increment(n=1){const p=this.progress;this.progress=Math.min(this.target,this.progress+n); if(this.isComplete){this.status='completed';this.completedAt ||= Date.now();}return this.progress!==p;}incrementDistinct(v,n=1){this.distinctValues=this.distinctValues||[];if(this.distinctValues.includes(v))return false;this.distinctValues.push(v);return this.increment(n);}pushHistoryValue(v){this.historyValues.push(v);return true;}walk(fn){fn(this);this.children.forEach(c=>c.walk(fn));}}
class Tree{constructor(def){this.id=def.id;this.title=def.title;this.description=def.description||'';this.nodes=new Map(); const rawRoot=def.root||{id:def.id+':root',type:'group',target:1,children:[]}; this.root=new Node(rawRoot); this.root.children=(rawRoot.children||[]).map(r=>{const n=new Node(r);this.nodes.set(n.id,n);return n}); this.nodes.set(this.root.id,this.root);this.refresh();}find(id){return this.nodes.get(id)||null}availableLeaves(){return this.root.children.filter(n=>!n.isComplete && (n.requires||[]).every(id=>this.find(id)?.isComplete))}refresh(){this.root.progress=this.root.children.length? (this.root.children.every(n=>n.isComplete)?1:0):this.root.progress;this.root.target=1;if(this.root.isComplete){this.root.status='completed';this.root.completedAt ||= Date.now();}}toJSON(){return {id:this.id,title:this.title,description:this.description,root:{id:this.root.id,status:this.root.status,progress:this.root.progress,target:this.root.target,completedAt:this.root.completedAt,children:this.root.children.map(n=>({id:n.id,type:n.type,status:n.status,progress:n.progress,target:n.target,params:n.params,requires:n.requires,completedAt:n.completedAt}))}}}}
class Planner{constructor(memory){this.memory=memory;}restoreOrCreate(id){return new Tree(window.BlueFox3D.Missions.getDefinition(id))} nextAction(tree){const n=tree.availableLeaves()[0];return n?{nodeId:n.id,type:n.type,title:n.id,params:n.params||{},issuedAt:Date.now()}:null} assess(){return null}}
class Bridge{constructor(engine){this.engine=engine;}context(){return {mapId:'crystal'}}}
const window={BlueFox3D:{},CustomEvent:CE,localStorage:{getItem(){return null},setItem(){},removeItem(){}},addEventListener(t,f){if(!listeners.has(t))listeners.set(t,new Set);listeners.get(t).add(f)},removeEventListener(t,f){listeners.get(t)?.delete(f)},dispatchEvent(e){events.push({type:e.type,detail:e.detail});for(const f of [...(listeners.get(e.type)||[])])f(e);return true},setTimeout(){return 0},clearTimeout(){},setInterval(){return 0},clearInterval(){},queueMicrotask(cb){cb()},performance:{now:()=>1000},console};window.window=window;window.globalThis=window;
const BF=window.BlueFox3D;BF.getProgressionState=()=>({inventory:{}});BF.BibleCatalog=[
{id:'T01',title:'T01',pattern:'OBSERVE_TARGET',trigger:{type:'manual',count:1},initialState:'active',targetBinding:'definition',prerequisites:[],priority:100,slots:{study:{title:'study',target:1,params:{objectId:'LANDMARK-CRASH-CAPSULE-001'}}}},
{id:'T02',title:'T02',pattern:'COLLECT_THEN_REWARD',trigger:{type:'progression.mission_completed',missionId:'T01',count:1},initialState:'active',prerequisites:['T01'],priority:96,slots:{collect:{title:'collect',requirements:[{title:'a',target:1,params:{kind:'wood'}}]}}}
];
BF.BiblePatterns={OBSERVE_TARGET:{steps:[{slot:'study',action:'observe',requires:[]}],autonomyAxis:'research'},COLLECT_THEN_REWARD:{steps:[{slot:'collect',action:'collect',requires:[]}],autonomyAxis:'collection'}};
BF.BibleContractV01={validateCatalog(){return {ok:true,errors:[],warnings:[]}}};
BF.Missions={definitions:{},normalizeActionType:x=>String(x||'').toLowerCase(),getDefinition(id){return this.definitions[id]||null},MissionMemory:Memory,MissionPlanner:Planner,ActionBridge:Bridge,MissionStatus:{COMPLETED:'completed'},ActionType:{COLLECT:'collect',EXTRACT:'extract',OBSERVE:'observe',INSPECT:'inspect',ANALYZE:'analyze',RESEARCH:'research',CRAFT:'craft',BUILD:'build',EXPLORE_ZONE:'explore_zone',TRAVEL:'travel',REST:'rest',EAT:'eat'}};
BF.registerMissionDefinitions=(defs)=>{defs.forEach(d=>BF.Missions.definitions[d.id]=d);return defs.length};
const subs=new Set();BF.ObjectEvents={types:{PHENOMENON_OBSERVED:'PHENOMENON_OBSERVED',OBJECT_INSPECTED:'OBJECT_INSPECTED',OBJECT_ANALYZED:'OBJECT_ANALYZED',RESOURCE_COLLECTED:'RESOURCE_COLLECTED',RESOURCE_EXTRACTED:'RESOURCE_EXTRACTED',OBJECT_SEEN:'OBJECT_SEEN',NPC_REACTION:'NPC_REACTION'},subscribe(fn){subs.add(fn);return()=>subs.delete(fn)},siteContext(){return null}};
const context=vm.createContext({window,console,CustomEvent:CE,performance:window.performance,setTimeout:window.setTimeout,clearTimeout:window.clearTimeout,setInterval:window.setInterval,clearInterval:window.clearInterval,Promise});
vm.runInContext(fs.readFileSync(path.join(ROOT,'engine/mission-manager.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(path.join(ROOT,'engine/bible-runtime-v0-1-unified.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(objectFile,'utf8'),context);
const engine={currentMapId:'crystal',callbacks:{onAction(){},onStatus(){}},character:{root:{position:{distanceTo(){return 0}}},target:{}},pendingInteraction:null,currentRoutine:null,pendingGate:null,pendingZoneExploration:null,transitioning:false,currentMap:{interactables:[]}};
const manager=BF.Missions.MissionManager.create({engine});engine.missionManager=manager;BF.currentEngine=engine;BF.getMissionState=()=>manager.getState();BF.bibleRuntime.activateInitialMissions();
assert.equal(manager.memory.state.missionLifecycle.T01.status,'active');
assert.equal(BF.bibleRuntime.missionLifecycleStatuses.get('T01'),'active');
console.log('leavesBefore',manager.trees.get('T01').availableLeaves().map(n=>n.id)); manager.currentAction={missionId:'T01',nodeId:'T01:study',type:'observe',instanceId:'crash-1',params:{}};
const ev={id:'ev1',type:'PHENOMENON_OBSERVED',objectId:'LANDMARK-CRASH-CAPSULE-001',instanceId:'crash-1',mapId:'crystal',tags:['landmark'],detail:{missionId:'T01',missionNodeId:'T01:study',instanceId:'crash-1',objectId:'LANDMARK-CRASH-CAPSULE-001',kind:'crash_capsule',subject:'landmark'}};
const consumed=manager.consumeObjectEvent(ev);
console.log('root',manager.trees.get('T01').root,'node',manager.trees.get('T01').find('T01:study'),'gate',BF.bibleRuntime.completionGateState('T01')); console.log('consumed',consumed,'life',manager.memory.state.missionLifecycle,'active',manager.activeMissionIds,'baseline',Object.fromEntries(BF.bibleRuntime.missionLifecycleStatuses));
assert.equal(manager.memory.state.missionLifecycle.T01.status,'completed');
assert.equal(manager.memory.state.missionLifecycle.T02.status,'active');
assert.ok(manager.activeMissionIds.includes('T02'));
console.log('PASS',objectFile);
