const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=process.env.BLUEFOX_ROOT||path.resolve(__dirname,'..');
const window={BlueFox3D:{},localStorage:{getItem:()=>null,setItem(){},removeItem(){}},addEventListener(){},removeEventListener(){},dispatchEvent(){},setTimeout(){return 0},clearTimeout(){},setInterval(){return 0},clearInterval(){},queueMicrotask(){},performance:{now:()=>0},document:null,CustomEvent:function(t,i){this.type=t;this.detail=i?.detail}};window.window=window;
const BF=window.BlueFox3D;BF.BiblePatterns={SEQUENCE_ACTIONS:{steps:[]},NARRATIVE_ONLY:{steps:[],narrativeOnly:true}};
const ctx=vm.createContext({window,console,performance:window.performance,CustomEvent:window.CustomEvent,setTimeout:window.setTimeout,clearTimeout:window.clearTimeout,setInterval:window.setInterval,clearInterval:window.clearInterval,Promise});
vm.runInContext(fs.readFileSync(path.join(root,'data','bible-catalog.js'),'utf8'),ctx);let code=fs.readFileSync(path.join(root,'engine','bible-runtime-v0-1-unified.js'),'utf8');code=code.replace(/\n\s*runtime\.start\(\);\n\}\)\(window\);\s*$/,'\n})(window);');vm.runInContext(code,ctx);const by=id=>BF.BibleCatalog.find(m=>m.id===id),compile=id=>BF.bibleRuntime.compileMission(by(id));
const f=compile('OPP-FAU-01');assert(f);assert.equal(f.root.children[0].params.sameTarget,true);assert.equal(f.root.children[1].params.sameTarget,true);assert.deepEqual(Array.from(f.root.children[1].requires),['OPP-FAU-01:firstLook']);
const adr=compile('OPP-ADR-03');assert.equal(adr.root.children.find(n=>n.id.endsWith(':optionalDebris')).optional,true);assert.equal(adr.root.children.find(n=>n.id.endsWith(':lastLook')).optional,false);
const oasis=compile('OPP-OASIS-01');assert.equal(oasis.root.children.find(n=>n.id.endsWith(':optionalSample')).optional,true);
for(const id of ['OPP-MET-01','OPP-MET-02','OPP-GEO-01','OPP-MET-03']){const c=compile(id);for(const n of c.root.children.filter(n=>n.type==='research')) assert(Number(n.params.duration)>0,`${id}: duration lost by compiler`);}
const civ=by('OPP-CIV-02');assert.equal(BF.bibleRuntime.eventMatchesTrigger(civ.trigger,{type:'exploration.map_discovered',featuredMicroSceneIds:['MSC-CUSTOM-SHADOW-ROCKY-001']}),true);assert.equal(BF.bibleRuntime.eventMatchesTrigger(civ.trigger,{type:'exploration.map_discovered',featuredMicroSceneIds:['MSC-CUSTOM-SHADOW-ROCKY']}),false);assert.equal(BF.bibleRuntime.eventMatchesTrigger(civ.trigger,{type:'exploration.map_discovered',featuredMicroSceneIds:[]}),false);
console.log('PASS OPP compiler/runtime contract: SAME-INSTANCE survives compilation + optional nodes + research durations + exact MSC trigger');
