const fs = require('fs');
const vm = require('vm');
const path = require('path');
const assert = require('assert');
const ROOT = path.join(__dirname, '..');
const window = { BlueFox3D:{} }; window.window = window;
vm.runInNewContext(fs.readFileSync(path.join(ROOT,'data/bible-catalog.js'),'utf8'), window, {filename:'bible-catalog.js'});
const BF=window.BlueFox3D;
const byId=new Map(BF.BibleCatalog.map(m=>[m.id,m]));
assert(BF.BibleCatalog.length >= 282,'PROS doit conserver les 279 missions antérieures + ses 3 missions sans bloquer les lots ultérieurs');
for(const id of ['PROS-01','PROS-03','PROS-02']) assert(byId.has(id),`${id} absente`);
assert(!byId.has('PROS-04'));
const p1=byId.get('PROS-01'), p3=byId.get('PROS-03'), p2=byId.get('PROS-02');
assert.equal(p1.pattern,'SEQUENCE_ACTIONS');
assert.equal(p1.trigger.type,'exploration.map_discovered');
assert.equal(p1.trigger.direction,'south');
assert.equal(p1.mapGeneration.requiredMicroScenes[0].id,'MSC-CUSTOM-BASALT-RIFT');
assert.equal(p1.mapGeneration.requiredObjects[0].type,'resonant_basalt');
const compare=p1.sequence.find(s=>s.slot==='compare');
assert.equal(compare.target,2); assert.equal(compare.params.distinctBy,'cuoType');
assert.deepStrictEqual(Array.from(compare.params.cuoTypes),['resonant_basalt','strong_rock','large_rock','needle']);
const resonance=p1.sequence.find(s=>s.slot==='resonance');
const sample=p1.sequence.find(s=>s.slot==='sample');
assert.equal(resonance.params.cuoType,'resonant_basalt');
assert.equal(sample.params.cuoType,'resonant_basalt');
assert.equal(sample.params.relation.fromSlot,'resonance');
assert.deepStrictEqual(Array.from(sample.params.relation.sameBy),['instanceId']);
assert.deepStrictEqual(Array.from(p3.prerequisites),['PROS-01','DRN-04']);
assert.equal(p3.proximityContexts[0].microSceneId,'MSC-CUSTOM-ETABLI-VIDE');
assert.deepStrictEqual(Array.from(p3.sequence.map(s=>s.slot)),['workbench','optimize'],'PROS-03 ne doit pas dupliquer DRN-03/04');
assert(p3.description.includes('déjà été validé par DRN-04'),'PROS-03 doit annoncer qu elle optimise un cycle déjà validé par DRN-04');
assert(!p3.description.includes('valider successivement'),'PROS-03 ne doit plus annoncer une revalidation post-optimisation absente de sa séquence');
const optimize=p3.sequence.find(s=>s.slot==='optimize');
assert.equal(optimize.params.requiresShelter,true,'la consommation doit nécessiter l accès infrastructure/camp');
const consume=optimize.params.inventoryConsume;
assert.equal(JSON.stringify(consume.map(x=>[x.inventoryKey,x.quantity])),JSON.stringify([['magnetic_ore',20],['crystal',10],['parts',5]]));
assert.equal(p3.worldEventRequirements,undefined,'PROS-03 ne doit pas réécouter une seconde fois les événements déjà possédés par DRN-03/04');
assert.equal(p3.runtimeValidation,undefined,'PROS-03 ne doit pas créer un runtime missionnel parallèle');
assert.deepStrictEqual(Array.from(p2.prerequisites),['PROS-03']);
assert.equal(p2.trigger.direction,'east');
assert.equal(p2.mapGeneration.requiredMicroScenes[0].id,'MSC-CUSTOM-COMPOSANT-RUIN');
assert.equal(p2.mapGeneration.requiredObjects[0].type,'relay_block');
const o=p2.sequence.find(s=>s.slot==='observeModule'), c=p2.sequence.find(s=>s.slot==='collectModule');
assert.equal(o.params.cuoType,'relay_block');
assert.equal(c.params.cuoType,'relay_block');
assert.equal(c.params.relation.fromSlot,'observeModule');
assert.deepStrictEqual(Array.from(c.params.relation.sameBy),['instanceId']);
const src=fs.readFileSync(path.join(ROOT,'data/bible-catalog.js'),'utf8');
for(const forbidden of ['stealth_runtime','infiltration_runtime','pure_mineral','hidden_vein','pros_bridge']) assert(!src.includes(forbidden),`pseudo système interdit: ${forbidden}`);
console.log('PROS IMI contract: PASS');
