const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=process.env.BLUEFOX_ROOT||path.resolve(__dirname,'..');
const store=new Map();const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem(k,v){store.set(k,String(v))},removeItem(k){store.delete(k)}};
const listeners={};const window={BlueFox3D:{},localStorage,addEventListener(t,f){listeners[t]=f},removeEventListener(){},dispatchEvent(){},setTimeout(){return 0},clearTimeout(){},setInterval(){return 0},clearInterval(){},queueMicrotask(){},performance:{now:()=>0},document:null,CustomEvent:function(t,i){this.type=t;this.detail=i?.detail}};window.window=window;const BF=window.BlueFox3D;BF.BiblePatterns={SEQUENCE_ACTIONS:{steps:[]},NARRATIVE_ONLY:{steps:[],narrativeOnly:true}};
const ctx=vm.createContext({window,console,performance:window.performance,CustomEvent:window.CustomEvent,setTimeout:window.setTimeout,clearTimeout:window.clearTimeout,setInterval:window.setInterval,clearInterval:window.clearInterval,Promise});
vm.runInContext(fs.readFileSync(path.join(root,'engine/progression-registry.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(root,'data/bible-catalog.js'),'utf8'),ctx);
let code=fs.readFileSync(path.join(root,'engine/bible-runtime-v0-1-unified.js'),'utf8');code=code.replace(/\n\s*runtime\.start\(\);\n\}\)\(window\);\s*$/,'\n})(window);');vm.runInContext(code,ctx);
const rt=BF.bibleRuntime,by=new Map(BF.BibleCatalog.map(m=>[m.id,m])),f1=by.get('FIN-01'),f2=by.get('FIN-02');rt.catalog=[f1,f2];rt.byId=new Map([[f1.id,f1],[f2.id,f2]]);
function node(id,done=false){return{id,progress:done?1:0,target:1,isComplete:done,increment(){if(this.isComplete)return false;this.progress=1;this.isComplete=true;return true}}}
const synth=node('FIN-01:synthesizeCore',true),integrate=node('FIN-02:integrateCore'),depart=node('FIN-02:depart');const tree1={find:id=>id===synth.id?synth:null,availableLeaves:()=>[],refresh(){}};const tree2={find(id){return id===integrate.id?integrate:id===depart.id?depart:null},availableLeaves(){if(!integrate.isComplete)return[integrate];return depart.isComplete?[]:[depart]},refresh(){}};
const facts={'endChoice:decision':{choiceId:'return'},'dip03:temple-map':{mapId:'custom-map-33-temple-magnet'}};const lifecycle={'FIN-01':{status:'active'},'FIN-02':{status:'available'}};const memory={state:{missionLifecycle:lifecycle,researchUnlocks:{}},getFact(k,d=null){return Object.prototype.hasOwnProperty.call(facts,k)?facts[k]:d},setFact(k,v){if(v==null)delete facts[k];else facts[k]=v;return true},save(){},saveTree(){}};const manager={memory,trees:new Map([['FIN-01',tree1],['FIN-02',tree2]]),syncLifecycleFromTrees(){},reevaluatePendingActivations(){},catalogController:{schedule(){}},publish(){}};rt.manager=()=>manager;
assert.equal(BF.getProgressionState().inventory.resonant_navigation_core,undefined);
assert.equal(rt.reconcileSlotInventoryGrantEffects(),true);assert.equal(BF.getProgressionState().inventory.resonant_navigation_core,1,'FIN-01 doit créer physiquement le Noyau dans ProgressionRegistry');assert.equal(facts['fin:resonant-core'].inventoryKey,'resonant_navigation_core');
lifecycle['FIN-01'].status='completed';lifecycle['FIN-02'].status='active';BF.currentEngine={currentMapId:'crystal',callbacks:{onStatus(){}}};assert.equal(rt.handleFinalCoreIntegration({type:'interaction.analyze',cuoType:'crash_capsule',mapId:'crystal'}),true);assert.equal(BF.getProgressionState().inventory.resonant_navigation_core,0,'FIN-02 doit retirer le Noyau du stock canonique');assert.equal(BF.getProgressionState().consumed.resonant_navigation_core,1,'ProgressionRegistry doit tracer la consommation/transfert');assert.equal(facts['fin:capsule-core-integrated'].componentId,'resonant_navigation_core');assert.equal(integrate.isComplete,true);
console.log('PASS END-B ProgressionRegistry: FIN-01 grants physical core, FIN-02 atomically consumes/transfers it into capsule');
