const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');const root=process.env.BLUEFOX_ROOT||path.resolve(__dirname,'..');
const listeners={};const window={BlueFox3D:{},localStorage:{getItem:()=>null,setItem(){},removeItem(){}},addEventListener(t,f){listeners[t]=f},removeEventListener(){},dispatchEvent(){},setTimeout(){return 0},clearTimeout(){},setInterval(){return 0},clearInterval(){},queueMicrotask(){},performance:{now:()=>0},document:null,CustomEvent:function(t,i){this.type=t;this.detail=i?.detail}};window.window=window;const BF=window.BlueFox3D;BF.BiblePatterns={SEQUENCE_ACTIONS:{steps:[]},NARRATIVE_ONLY:{steps:[],narrativeOnly:true}};
const inventory={};const transactions={};BF.grantInventory=(key,qty,detail={})=>{inventory[key]=(inventory[key]||0)+qty;return qty};BF.consumeInventoryPoolOnce=(id,keys,qty)=>{if(transactions[id])return transactions[id];const key=keys[0],available=inventory[key]||0;if(available<qty)return 0;inventory[key]=available-qty;transactions[id]=qty;return qty};
const ctx=vm.createContext({window,console,performance:window.performance,CustomEvent:window.CustomEvent,setTimeout:window.setTimeout,clearTimeout:window.clearTimeout,setInterval:window.setInterval,clearInterval:window.clearInterval,Promise});vm.runInContext(fs.readFileSync(path.join(root,'data/bible-catalog.js'),'utf8'),ctx);let code=fs.readFileSync(path.join(root,'engine/bible-runtime-v0-1-unified.js'),'utf8');code=code.replace(/\n\s*runtime\.start\(\);\n\}\)\(window\);\s*$/,'\n})(window);');vm.runInContext(code,ctx);
const rt=BF.bibleRuntime,by=new Map(BF.BibleCatalog.map(m=>[m.id,m])),f1=by.get('FIN-01'),f2=by.get('FIN-02');rt.catalog=[f1,f2];rt.byId=new Map([[f1.id,f1],[f2.id,f2]]);const facts={'endChoice:decision':{choiceId:'stay'},'dip03:temple-map':{mapId:'custom-map-33-temple-magnet'}};const lifecycle={'END-CHOICE':{status:'completed'},'FIN-01':{status:'available'},'FIN-02':{status:'available'}};
function node(id,done=false){return{id,progress:done?1:0,target:1,isComplete:done,increment(){if(this.isComplete)return false;this.progress=1;this.isComplete=true;return true}}}
const synth=node('FIN-01:synthesizeCore',true),depart=node('FIN-02:depart'),integrate=node('FIN-02:integrateCore');const tree1={find:id=>id===synth.id?synth:null,availableLeaves:()=>[],refresh(){}};const tree2={find(id){return id===depart.id?depart:id===integrate.id?integrate:null},availableLeaves(){if(!integrate.isComplete)return[integrate];return depart.isComplete?[]:[depart]},refresh(){}};
const memory={state:{missionLifecycle:lifecycle,researchUnlocks:{}},getFact(k,d=null){return Object.prototype.hasOwnProperty.call(facts,k)?facts[k]:d},setFact(k,v){if(v==null)delete facts[k];else facts[k]=v;return true},save(){},saveTree(){}};const manager={memory,trees:new Map([['FIN-01',tree1],['FIN-02',tree2]]),syncLifecycleFromTrees(){if(depart.isComplete)lifecycle['FIN-02'].status='completed'},reevaluatePendingActivations(){},catalogController:{schedule(){}},publish(){}};rt.manager=()=>manager;
assert.equal(rt.prerequisitesSatisfied(f1),false,'Rester doit bloquer FIN-01');facts['endChoice:decision']={choiceId:'return'};assert.equal(rt.prerequisitesSatisfied(f1),true,'Retour doit autoriser FIN-01');
lifecycle['FIN-01'].status='active';assert.equal(rt.reconcileSlotInventoryGrantEffects(),true,'la synthèse doit produire le Noyau physique');assert.equal(inventory.resonant_navigation_core,1,'le Noyau doit exister dans l inventaire canonique');assert.equal(facts['fin:resonant-core'].inventoryKey,'resonant_navigation_core');assert.equal(rt.reconcileSlotInventoryGrantEffects(),false,'le grant doit être idempotent après le fait persistant');assert.equal(inventory.resonant_navigation_core,1);
lifecycle['FIN-01'].status='completed';lifecycle['FIN-02'].status='active';BF.currentEngine={currentMapId:'crystal',callbacks:{onStatus(){}},isFinalCapsuleSequenceActive:()=>false,beginFinalCapsuleSequence(o){starts++;assert.equal(o.missionId,'FIN-02');return true}};
inventory.resonant_navigation_core=0;assert.equal(rt.handleFinalCoreIntegration({type:'interaction.analyze',cuoType:'crash_capsule',mapId:'crystal'}),false,'sans Noyau physique l intégration doit échouer');assert.equal(integrate.isComplete,false);assert.equal(facts['fin:capsule-core-integrated'],undefined);
inventory.resonant_navigation_core=1;assert.equal(rt.handleFinalCoreIntegration({type:'interaction.analyze',cuoType:'crash_capsule',mapId:'crystal'}),true,'l analyse réelle de la capsule doit consommer le Noyau');assert.equal(inventory.resonant_navigation_core,0,'le Noyau doit être transféré/consommé par la capsule');assert.equal(integrate.isComplete,true);assert.equal(facts['fin:capsule-core-integrated'].inventoryKey,'resonant_navigation_core');
let starts=0;assert.equal(rt.reconcileFinalDeparture(),true);assert.equal(starts,1);assert.equal(rt.onFinalDepartureCompleted({missionId:'FIN-02',mapId:'crystal'}),true);assert.equal(depart.isComplete,true);assert(facts['fin:departure-completed']);
console.log('PASS END-B runtime: physical resonant core granted to canonical inventory, required and consumed by capsule before final departure');
