const fs=require('fs');const vm=require('vm');const path=require('path');const assert=require('assert');
const root=path.resolve(__dirname,'..');
const w={BlueFox3D:{}};w.window=w;vm.runInNewContext(fs.readFileSync(path.join(root,'data/bible-catalog.js'),'utf8'),{window:w,console});
const cat=w.BlueFox3D.BibleCatalog,by=new Map(cat.map(m=>[m.id,m]));
for(const id of ['POSTDIP-01','TP-01','TP-02','TP-03','TP-04','TP-05','TP-06','TP-07','TP-08','TP-09']) assert(by.has(id),`${id} absente`);
assert.equal(cat.length,322,'R-TP-A préservé dans le catalogue END/FIN à 322 missions');
const post=by.get('POSTDIP-01');
assert.deepStrictEqual(Array.from(post.prerequisites),['ENE-15-C','DIP-03','ENE-14']);
assert(post.requiredFacts.includes('shared_civilization_knowledge'));
assert.equal(post.sequence.find(s=>s.slot==='phenReturn').optional,true,'PHEN doit enrichir sans bloquer POSTDIP');
assert.equal(post.sequence.find(s=>s.slot==='phenScout').params.actor,'scout');
assert(post.narrative.progress[0].text.includes("Les mesures étaient bonnes"),'pensée POSTDIP verrouillée absente');
const t1=by.get('TP-01');
assert.deepStrictEqual(Array.from(t1.prerequisites),['POSTDIP-01','ENE-15-C']);
assert(t1.requiredFacts.includes('civilization:research:teleport-hypothesis-v1'));
const t2=by.get('TP-02');
assert.equal(t2.sequence[0].params.actor,'scout');assert.equal(t2.sequence[0].params.remote,true);
const t3=by.get('TP-03'),t4=by.get('TP-04');
assert.equal(t3.proximityContexts[0].microSceneId,'MSC-CUSTOM-ETABLI-VIDE');
assert.equal(t3.proximityContexts[0].inventoryConsume.quantity,3);
assert.equal(t4.proximityContexts[0].inventoryConsume.quantity,4);
const t5=by.get('TP-05'),s5=Object.fromEntries(t5.sequence.map(s=>[s.slot,s]));
assert.equal(t5.mapGeneration.requiredMicroScenes[0].id,'MSC-CUSTOM-COMPOSANT-RUIN');
assert.equal(s5.reachReceiver.params.completionArrivalFact,'tp05:receiverMap');
assert.equal(s5.returnWorkbench.params.toMapId,'crystal');
assert.equal(s5.remoteWitness.params.actor,'scout');assert.equal(s5.remoteWitness.params.remote,true);
assert.equal(s5.remoteWitness.params.cuoType,'relay_block');
assert.equal(s5.remoteWitness.params.requiredMapFact,'tp05:receiverMap');
assert.equal(t5.proximityContexts.find(x=>x.slot==='transfer').inventoryConsume.quantity,5);
const t6=by.get('TP-06');assert(t6.narrative.completed[0].includes('Aucun passage direct'));
const t7=by.get('TP-07');assert.equal(t7.sequence[0].params.completionArrivalFact,'tp07:hubSite');
const t8=by.get('TP-08'),p8=t8.persistentWorldScenes[0];
assert.equal(p8.microSceneId,'MSC-CUSTOM-ASTROLOGY');assert.equal(p8.requiredMapFact,'tp07:hubSite');assert.equal(p8.placement.mode,'player');
assert.equal(p8.kind,'teleporter_site');assert.equal(p8.contextRole,'teleporter_anchor');assert.equal(p8.progressSlotWhenResolved,'placeAnchor');
const t9=by.get('TP-09'),n9=t9.sequence.find(s=>s.slot==='networkProof');
assert.equal(n9.params.actor,'scout');assert.equal(n9.params.remote,true);assert.equal(n9.params.distinctBy,'mapId');assert.equal(n9.target,4);
const stock=Object.fromEntries(t9.stockBackedSlots.map(x=>[x.slot,x]));
assert.equal(stock.minerals.maximum,100);assert.equal(stock.rareMinerals.maximum,30);assert.equal(stock.parts.maximum,50);assert.equal(stock.cores.maximum,20);assert.equal(stock.fibers.maximum,100);assert.equal(stock.accumulators.maximum,10);assert.equal(stock.plantBiocapital.maximum,50);
assert(!JSON.stringify(t9).includes('adaptive_biomass'),'TP-09 ne doit pas utiliser de biomasse adaptative');
assert(!t9.stockBackedSlots.some(x=>x.inventoryKey==='deployed_beacon'),'les 4 balises sont une infrastructure, pas un stock consommable');
assert.equal(by.has('TP-10'),true);assert.equal(by.has('TP-11'),true);
console.log('PASS R-TP-A préservé + phase TP-10/TP-11 ouverte');
