const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const w={BlueFox3D:{}};w.window=w;
vm.runInNewContext(fs.readFileSync(path.join(root,'data/bible-catalog.js'),'utf8'),{window:w,console});
const cat=w.BlueFox3D.BibleCatalog, by=new Map(cat.map(m=>[m.id,m]));
for(const id of ['POSTDIP-01','TP-01','TP-02','TP-03','TP-04','TP-05','TP-06','TP-07','TP-08','TP-09','TP-10','TP-11']) assert(by.has(id),`${id} absente`);
assert.equal(cat.length,322,'R-TP complet + TP-AFTER préservés dans le catalogue END/FIN à 322 missions');
const t10=by.get('TP-10'), t11=by.get('TP-11');
assert.deepStrictEqual(Array.from(t10.prerequisites),['TP-09']);
assert.equal(t10.sequence.length,1); assert.equal(t10.sequence[0].slot,'assemble');
assert.equal(t10.sequence[0].params.catalogManaged,true);assert.equal(t10.sequence[0].params.eventDriven,true);
assert.equal(t10.runtimeValidation.type,'teleporter-activation');
const effects=t10.effects;assert.equal(effects.length,7);assert.equal(effects[0].quantity,30);assert.equal(effects[1].quantity,70);assert.equal(effects.find(x=>x.inventoryKey==='parts').quantity,50);assert.equal(effects.find(x=>x.inventoryKey==='core').quantity,20);assert.equal(effects.find(x=>x.inventoryKey==='fiber').quantity,100);assert.equal(effects.find(x=>x.inventoryKey==='accumulator').quantity,10);assert.equal(effects.find(x=>x.inventoryKey==='biocapital').quantity,50);
assert.deepStrictEqual(Array.from(t11.prerequisites),['TP-10']);
const s=Object.fromEntries(t11.sequence.map(x=>[x.slot,x]));
assert.equal(s.calibrateNetwork.params.catalogManaged,true);assert.equal(s.calibrateNetwork.params.eventDriven,true);assert.equal(s.inertTransfer.params.catalogManaged,true);assert.equal(s.inertTransfer.params.eventDriven,true);assert.deepStrictEqual(Array.from(s.inertTransfer.requires),['calibrateNetwork']);assert.deepStrictEqual(Array.from(s.outbound.requires),['inertTransfer']);assert.equal(t11.runtimeValidation.calibrationSlot,'calibrateNetwork');assert.equal(t11.runtimeValidation.inertTransferSlot,'inertTransfer');
assert.equal(s.outbound.params.direction,'teleport-outbound');
assert.equal(s.outbound.params.transitionSource,'teleporter');
assert.equal(s.outbound.params.transitionMode,'teleport');
assert.equal(s.returnHub.params.direction,'teleport-return');
assert.equal(s.returnHub.params.transitionSource,'teleporter');
assert.equal(s.returnHub.params.transitionMode,'teleport');
const t8=by.get('TP-08'); assert.equal(t8.persistentWorldScenes[0].microSceneId,'MSC-CUSTOM-ASTROLOGY');
const t9=by.get('TP-09'); assert.equal(t9.sequence.find(x=>x.slot==='networkProof').target,4);
console.log('PASS R-TP-B/C catalog TP-10/11 + construction consumption + préservation TP-01→09');
