const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
class V3{constructor(x=0,y=0,z=0){this.x=x;this.y=y;this.z=z}clone(){return new V3(this.x,this.y,this.z)}copy(v){this.x=v.x;this.y=v.y;this.z=v.z;return this}set(x,y,z){this.x=x;this.y=y;this.z=z;return this}distanceTo(v){return Math.hypot(this.x-v.x,this.z-v.z)}}
const events=[];
const w={BlueFox3D:{maps:{hub:{biome:'alien'},dest:{biome:'forest'}}},performance:{now:()=>100},setTimeout:(fn)=>{fn();return 1},clearTimeout(){},CustomEvent:class{constructor(type,o={}){this.type=type;this.detail=o.detail}},dispatchEvent(e){events.push(e)},console};w.window=w;
let src=fs.readFileSync(path.join(root,'engine/world-engine.js'),'utf8').replace('BF.mount = async function mount(options) {','BF.__WorldEngine = WorldEngine;\n  BF.mount = async function mount(options) {');
vm.runInNewContext(src,{window:w,console,performance:w.performance,setTimeout:w.setTimeout,CustomEvent:w.CustomEvent});
const P=w.BlueFox3D.__WorldEngine.prototype;
const e=Object.create(P);e.THREE={Vector3:V3};e.currentMap={colliders:[]};e.character={radius:.64,walkableRegions:[{minX:-10,maxX:10,minZ:-10,maxZ:10}],root:{position:new V3(0,0,0)},lastSafePosition:new V3(),enabled:true,stop(){},setTarget(){},facePoint(){}};
let p=P.safeTeleportArrival.call(e,{x:0,z:0},2,4);assert(p);assert(Math.hypot(p.x,p.z)>=2 && Math.hypot(p.x,p.z)<=4);
e.currentMap.colliders=[{position:new V3(p.x,0,p.z),radius:4}];p=P.safeTeleportArrival.call(e,{x:0,z:0},2,4);assert(p,'doit chercher un autre angle sûr');
e.character.walkableRegions=[];assert.equal(P.safeTeleportArrival.call(e,{x:0,z:0},2,4),null,'aucun fallback sans région marchable');
// Transition directe connue: canonical event, isNew false, guard exploration, restauration contrôle.
const tr=Object.create(P);tr.THREE={Vector3:V3};tr.currentMapId='hub';tr.currentMap={colliders:[]};tr.discoveredMaps=new Set(['hub','dest']);tr.transitioning=false;tr.completedTransitions=3;tr.character={radius:.64,walkableRegions:[{minX:-20,maxX:20,minZ:-20,maxZ:20}],root:{position:new V3(0,0,0)},lastSafePosition:new V3(),enabled:true,stop(){},setTarget(){},facePoint(){}};tr.transitionElement={classList:{add(){},remove(){}}};tr.cameraController={captureViewState(){return{}},restoreViewState(){return true},resetBehindCharacter(){}};tr.savePosition=()=>{};tr.loadMap=async(id)=>{tr.currentMapId=id;tr.currentMap={colliders:[]};tr.character.walkableRegions=[{minX:-20,maxX:20,minZ:-20,maxZ:20}]};
(async()=>{const ok=await P.transitionToKnownMap.call(tr,'dest',{targetAnchor:{x:5,z:5},source:'teleporter',mode:'teleport',direction:'teleport-outbound'});assert.equal(ok,true);assert.equal(tr.transitioning,false);assert.equal(tr.character.enabled,true);assert.equal(tr.explorationRelocationGuard.mapId,'dest');const evt=events.find(x=>x.type==='bluefox:map-transition-completed');assert(evt);assert.equal(evt.detail.isNew,false);assert.equal(evt.detail.source,'teleporter');assert.equal(evt.detail.mode,'teleport');assert.equal(evt.detail.direction,'teleport-outbound');assert.equal(await P.transitionToKnownMap.call(tr,'unknown',{targetAnchor:{x:0,z:0}}),false);
// Aucun point sûr : la map cible peut être chargée pour connaître sa géométrie, mais le cycle doit revenir atomiquement à la map source, sans événement de réussite et avec contrôles restaurés.
tr.currentMapId='hub';tr.character.root.position.set(1,0,1);tr.character.lastSafePosition.copy(tr.character.root.position);tr.explorationRelocationGuard=null;const beforeEvents=events.length;tr.loadMap=async(id)=>{tr.currentMapId=id;tr.currentMap={colliders:[]};tr.character.walkableRegions=id==='dest'?[]:[{minX:-20,maxX:20,minZ:-20,maxZ:20}]};const refused=await P.transitionToKnownMap.call(tr,'dest',{targetAnchor:{x:5,z:5},source:'teleporter',mode:'teleport',direction:'teleport-outbound'});assert.equal(refused,false);assert.equal(tr.currentMapId,'hub');assert.equal(tr.character.root.position.x,1);assert.equal(tr.character.root.position.z,1);assert.equal(tr.character.enabled,true);assert.equal(tr.transitioning,false);assert.equal(events.length,beforeEvents,'un transfert refusé ne doit pas émettre map-transition-completed');
// Non-régression gate : le chemin historique continue de découvrir/charger et d'émettre le même événement sans metadata téléporteur.
tr.navigationRoute=[];tr.returningToBase=false;tr.autonomyMode='manual';tr.persistentNavigationIntent=null;tr.pendingGate={};tr.canDiscoverMap=()=>true;tr.safeEntryPosition=()=>new V3(3,0,3);tr.ensureUniqueMapName=()=>{};tr.saveDiscovery=()=>{};tr.narrativeMapName=id=>id;tr.callbacks={onAction(){},onMapDiscovered(){},onStatus(){}};tr.beginAutonomyGrace=()=>{};tr.clearPersistentNavigationIntent=()=>{};tr.navigateNextRouteStep=()=>{};tr.resumePersistentNavigation=()=>{};tr.moveToBaseCamp=()=>{};tr.loadMap=async(id)=>{tr.currentMapId=id;tr.currentMap={colliders:[]};tr.character.walkableRegions=[{minX:-20,maxX:20,minZ:-20,maxZ:20}]};const gateEventStart=events.length;await P.crossGate.call(tr,{userData:{exit:{targetMap:'dest',targetEntry:null,direction:'east'}}});assert.equal(tr.currentMapId,'dest');assert.equal(tr.character.enabled,true);assert.equal(tr.transitioning,false);const gateEvt=events.slice(gateEventStart).find(x=>x.type==='bluefox:map-transition-completed');assert(gateEvt);assert.equal(gateEvt.detail.direction,'east');assert.equal(gateEvt.detail.isNew,false);assert.equal(gateEvt.detail.source,undefined);assert.equal(gateEvt.detail.mode,undefined);console.log('PASS WorldEngine teleport known-map + safe arrival + atomic refusal + gate non-regression');})().catch(e=>{console.error(e);process.exit(1)});
